Develop
potepancamp/phiii pull request #1
Opened 2022-02-21 11:41 UTC by DJ-phi

課題の提出です

2022-02-21 12:34 UTC, nakanoTaku commented on app/controllers/potepan/products_controller.rb
> +  end
不要なアクション以外は削除しましょう！

2022-02-21 12:34 UTC, nakanoTaku commented on app/controllers/potepan/products_controller.rb
> +    # console
不要なコメントは削除しましょう！

2022-02-21 12:35 UTC, nakanoTaku commented on app/controllers/potepan/products_controller.rb
> +    @product = Spree::Product.find_by(id: params[:id])
`find_by` にする理由はありますか？

2022-02-21 12:35 UTC, nakanoTaku commented on app/views/layouts/_header.html.erb
> +            <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
コメントアウトする場合は必ず理由を書きましょう。不要な場合は削除しましょう。

2022-02-21 12:56 UTC, nakanoTaku commented on app/views/layouts/_header.html.erb
> +          <%= link_to("Home" , potepan_path)%>
`link_to`は、（）なくてokです！

2022-02-21 13:03 UTC, nakanoTaku commented on config/routes.rb
> +    resources :categories
こちら必要ですか？

2022-02-21 13:03 UTC, nakanoTaku commented on config/routes.rb
> +    resources :products
必要なアクションだけに絞りましょう。

2022-02-21 13:04 UTC, nakanoTaku commented on app/views/potepan/products/show.html.erb
> +              <%= link_to("Home" , potepan_path)%>
こちらも同様

2022-02-21 13:12 UTC, nakanoTaku commented on app/views/potepan/products/show.html.erb
> +          <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
`Time.now`でも現在日時を取得できますが、環境変数に依存して正しい日付が取得できない場合があります。
日本時間を正しく取得できるよう修正しましょう。

2022-02-21 13:14 UTC, nakanoTaku commented
幾つかコメントしましたので、ご確認下さい。
また、HerokuのURLが正しくありません。ソースを見る限りでも参考サイトと違う箇所がありそうです。
合わせて再度確認お願いします。

2022-02-22 02:48 UTC, hyo0306 reviewed
おつかれさまです！インラインでコメントしたので確認お願いします。また下記も確認お願いします↓
1. PRのタイトルと文言が適切ではないです。そのどのような機能のPRなのか、どのような実装をしたのかを説明するようにしてください。
2. 次の課題からブランチ名は何を実装するのかが伝わるようにしましょう。今回だと「商品詳細ページ」なので、それがわかるようなブランチ名にしましょう。
3. ページタイトルが動的に変わるようにしましょう
4. 関連商品一覧の表示、フォント（商品価格など）、ヘッダーのHOMEリンク、ホーム画面のレイアウトなどサンプルページと一致していない箇所が多いです。サンプルページと比較して問題ないことを確認してから提出しましょう

2022-02-22 02:48 UTC, hyo0306 commented on app/views/potepan/products/show.html.erb
> +            <h2>Single Product</h2>
動的に変えましょう
全体的に確認して同様の箇所があれば修正してください

2022-02-22 02:48 UTC, hyo0306 commented on app/views/potepan/products/show.html.erb
> +                      <%= image_tag(img.attachment(:small)) %>
画像がボケて表示されています。適切なサイズを選びましょう

2022-02-22 02:48 UTC, hyo0306 commented on app/views/potepan/products/show.html.erb
> +          <p>&copy; 2016-<%= Date.current.strftime("%Y年 %m月 %d日")%> Copyright Potepan Store .</p>
サンプルページと表示が違います。年をとりたいだけなのでstrftimeを使わずに取得しましょう（年だけとれるメソッドがあるはずです

2022-02-22 02:48 UTC, hyo0306 commented on app/views/potepan/products/show.html.erb
> +          <p>&copy; 2016-<%= Date.current.strftime("%Y年 %m月 %d日")%> Copyright Potepan Store .</p>
タイムゾーンを意識した日付にしましょう

2022-02-22 02:48 UTC, hyo0306 commented on app/views/layouts/_header.html.erb
> +          <%= link_to "Home" , potepan_path%>
"Home"のあとのスペースが不要、%>の前のスペースが足りないです
全体的に同様の箇所があるようなので確認/修正してください

2022-02-22 02:48 UTC, hyo0306 commented on config/routes.rb
> +    resources :products, only: [:show]
手

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +
不要な空行

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +
不要な空行

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +
不要な空行

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +  it "showにアクセスできるかどうか" do
テストケースとテスト内容が異なっています。これはレスポンスステータスが200になるかをテストしてますね

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +    get potepan_product_path(product.id)
`it "#porducts/:id レスポンスの中身が正しく取得できていること" do`でも呼び出す必要がありそうですね。どちらでも呼び出されるように共通化しましょう

2022-02-22 02:48 UTC, hyo0306 commented on spec/requests/potepan/products_spec.rb
> +      expect(response.body).to include product.images
products.imagesは配列なので、response.bodyに直接含まれることはないと思います
pryを挟んでproduct.imagesが空になっていないか確認しましょう。空だとテストデータを用意できていないので正しくテストできていないことになります

2022-02-22 02:48 UTC, hyo0306 commented on app/views/potepan/products/show.html.erb
> +          <p>&copy; 2016-<%= Date.current.strftime("%Y年 %m月 %d日")%> Copyright Potepan Store .</p>
ホーム画面にいくとこのロジックが反映されていないです。共通化しましょう

2022-02-25 14:15 UTC, nakanoTaku commented on spec/requests/potepan/products_spec.rb
> +      expect(response.body).to include product.images
19行目に記載してるので、17行目は不要になると思います。
確認お願いします。

2022-02-25 14:15 UTC, nakanoTaku commented
細かいですが、1点だけコメントしました。

2022-02-26 01:15 UTC, bary822 reviewed
レビュアーの福井です。修正ポイントをいくつかコメントしました。
ご確認ください。

2022-02-26 01:15 UTC, bary822 commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:datetime_jp] = '%Y年 %m月%d日'
この変更は必要でしょうか? `datetime_jp`というフォーマットを指定して日時表示を行っているコードを見つけることができませんでした。

2022-02-26 01:15 UTC, bary822 commented on config/database.yml
> +  #
不要なコメントなので削除しておいてください、

2022-02-26 01:15 UTC, bary822 commented on config/database.yml
>    password: <%= ENV['POTEPANEC_DATABASE_PASSWORD'] %>
これらの情報は既に`url`に含まれているため削除できます。Herokuにて中身を確認できるので一度見てみてください。

2022-02-26 01:15 UTC, bary822 commented on spec/helpers/appliction_helper_spec.rb
> +  describe 'full title helper' do
メソッドの単体テストを行うときは`describe`に`"#(メソッド名)"`と書くことが多いです。迷ったときは公式ドキュメントの書き方を参照してください。
https://relishapp.com/rspec/rspec-rails/v/2-0/docs/helper-specs/helper-spec

2022-02-26 01:15 UTC, bary822 commented on spec/helpers/appliction_helper_spec.rb
> +    it "When no pagetitle,return basetitle" do
テストにおいては`pagetitle`や`basetitle`など、実装の詳細に踏み込むべきではありません。
「どんな引数を与えたら、何が返ってくるか」というフォーマットで期待する挙動を記述しましょう。

2022-02-26 04:59 UTC, shungo0525 requested changes
レビュアーの松村です。
少しコメントしましたのでご確認ください

2022-02-26 04:59 UTC, shungo0525 commented on app/views/layouts/_footer.html.erb
> +  <!-- COPY RIGHT -->
インデントずれてます

2022-02-26 04:59 UTC, shungo0525 commented on spec/requests/potepan/products_spec.rb
> +  let(:product) {create(:product)}
` { create(:product) }`
ハッシュの前後にスペース欲しいですね

2022-02-26 10:03 UTC, masanarih0ri reviewed
少しコメントしました。

2022-02-26 12:43 UTC, codethefuture reviewed
コメントしました

2022-02-26 12:43 UTC, codethefuture commented on app/views/layouts/_footer.html.erb
> +<!-- LOGIN MODAL -->
ファイル名がfooterなのに、モーダルが2つ定義されているのは、この名前から推測できないことなのでやめましょう。

このファイル名を変更するか、モーダルを切り出してください。

2022-02-26 12:43 UTC, codethefuture commented on app/views/potepan/products/show.html.erb
> +<% provide(:title, @product.name) %>
ファイルの行数が長いので、いくつかのパーシャルへと切り出しましょう。

2022-02-26 12:43 UTC, codethefuture commented on app/views/potepan/sample/index.html.erb
>  <!DOCTYPE html>
app/views/layouts/application.html.erb内に定義されている部分がこのファイルに記載されています。重複されて出力されますので、app/views/layouts/application.html.erbがなんなのか調べてこのファイルを修正してみてください。

2022-02-27 00:45 UTC, shungo0525 requested changes
レビュアーの松村です。
すみません、昨日コメントできていないとこあったので少しコメントしました🙏

2022-02-27 00:45 UTC, shungo0525 commented on spec/helpers/appliction_helper_spec.rb
> +    it "タイトルが空白だった場合" do
itの文言は~することが一般的です。
他のところも確認をお願い致します。

2022-02-27 00:45 UTC, shungo0525 commented on spec/requests/potepan/products_spec.rb
> +
修正漏れです

2022-02-27 04:08 UTC, shungo0525 approved these changes
私からはLGTMです！
次のレビュアーからのコメントをお待ちください。

2022-02-27 09:29 UTC, kaizumoto reviewed
レビュアーの伊豆本です。
1点コメントしましたのでご確認ください。

2022-02-27 10:24 UTC, shimizzuu reviewed
レビュアーの清水です。
1点だけコメントしました。ご確認ください。

2022-02-27 10:24 UTC, shimizzuu commented on app/views/potepan/products/_light_section_show.html.erb
> +          <li class="active"><%= @product.name %></li>
パーシャルでインスタンス変数を使わないようにしましょう。

2022-02-27 11:32 UTC, shimizzuu approved these changes
私からはLGTMです。
もう1名のレビューをお待ち下さい。

2022-02-27 13:24 UTC, codethefuture approved these changes
マージ承認です

2022-02-28 13:54 UTC, merged