Categories
potepancamp/phiii pull request #2
Opened 2022-02-28 11:51 UTC by DJ-phi

カテゴリページの実装をしました！！
テストコードを追加しました

2022-02-28 13:53 UTC, kaizumoto commented
課題２と課題３の差分が表示されているので課題３だけプルリクエストに出すようにしてください。
[課題２](https://github.com/potepancamp/phiii/pull/1)のプルリクエストをマージし、categoriesに取り込みpushしてください。

2022-03-01 11:22 UTC, kaizumoto reviewed
レビュアーの伊豆本です。
差分が課題３の範囲に限定して頂いてありがとうございました。
コメントしましたのでご確認ください。
また、system specを記載してください。

2022-03-01 11:22 UTC, kaizumoto commented on app/views/potepan/categories/show.html.erb
> +                          <%= link_to potepan_category_url(taxon.id) do %>
どちらでも動くと思いますが、*_pathにしておくのが無難かと思います
https://railstutorial.jp/chapters/filling_in_the_layout?version=5.1#sec-rails_routes

2022-03-01 11:22 UTC, kaizumoto commented on spec/requests/potepan/categories_spec.rb
> +      expect(response.body).to include taxon.products.count.to_s
bodyの中で数値は該当箇所以外でもヒットするかと思いますのでsystem specで検証するのが良いかと思います。

2022-03-02 12:37 UTC, tsakamo71 requested changes
レビュアーの坂本です。

プルリクの名前を日本語で構いませんので、このプルリクを端的に表す文章で書いてください。
また説明書きの欄も本来は実装した仕様の内容などを書くべきです。

そのほかテストについてインラインで指摘しました。
実装は良さそうだと思います。

2022-03-02 12:37 UTC, tsakamo71 commented on spec/requests/potepan/categories_spec.rb
> +      within(".body") do
コントローラーのテストでwithinを使ってはいけません

2022-03-02 12:37 UTC, tsakamo71 commented on spec/requests/potepan/categories_spec.rb
> +require 'rails_helper'
テストが足りていないようです。
実装した仕様をテストすべきですので、何を実装したのかを考えテストを作成してください。

2022-03-02 14:49 UTC, shimizzuu reviewed
レビュアーの清水です。
コメントしましたのでご確認ください。

2022-03-03 01:02 UTC, kaizumoto reviewed
レビュアーの伊豆本です。
私からはLGTMです。もう一名のレビューをお待ちください。

2022-03-03 03:34 UTC, masanarih0ri reviewed
お疲れ様です。私からもLGTMです。

2022-03-03 04:01 UTC, merged